### ISSUE TITLE
Bugs in Setting Panel #KEYLOGGER

### ISSUE THREAD

**Issue by adhi1234** [PSNAppz/KeyLogger#2]
While using this software it has been found that form displayed after the Login Screen is asking for the E mail ID and password....and the mailing Time Interval is set to default...I cant reset it....

Awaiting for your Response....
![capture](https://cloud.githubusercontent.com/assets/11091122/8397405/badd4f72-1de7-11e5-9523-56c00468fc8f.PNG)

Thank You

**Comment by PSNAppz** [comment]
Well,
Its a pre-release and still in Beta stage.Thank you for pointing out the Bug.I'll fix it soon.

By,
The PSN AppZ

**Comment by PSNAppz** [comment]
Fixed !
